# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# syntax=docker/dockerfile:1

# Use Node.js LTS as the base image
FROM node:20-slim AS builder

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN --mount=type=cache,target=/root/.npm npm ci --ignore-scripts --omit-dev

# Copy source code
COPY . .

# Build the package
RUN --mount=type=cache,target=/root/.npm npm run build

# Install package globally
RUN --mount=type=cache,target=/root/.npm npm link

# Minimal image for runtime
FROM node:20-slim

# Copy built package from builder stage
# COPY specs/coingecko_openapi_v3.json /usr/local/scripts/coingecko-v3-openapi.json # Removed incorrect copy
COPY --from=builder /usr/local/lib/node_modules/@nic0xflamel/coingecko-mcp-server /usr/local/lib/node_modules/@nic0xflamel/coingecko-mcp-server
COPY --from=builder /usr/local/bin/coingecko-mcp-server /usr/local/bin/coingecko-mcp-server
COPY specs/ /usr/local/lib/node_modules/@nic0xflamel/coingecko-mcp-server/specs/

# Set default environment variables
ENV OPENAPI_MCP_HEADERS="{}"

# Set entrypoint
ENTRYPOINT ["coingecko-mcp-server"]
